
# Eureka Configurations:
# 
# These should generally be done in the Eureka Server / Client instances directly.
# The config-server is looked up through the Eureka service registry. Hence this configuration
# will only be available AFTER Eureka is up and running and clients have connected and looked
# up config-server.

eureka:
  client:
    registryFetchIntervalSeconds: 30 # only for local development.
  instance:
    leaseRenewalIntervalInSeconds: 30 # only for local development.

#spring.zipkin.base-url=${vcap.services.zipkin-service.credentials.uri}
#spring.rabbitmq.addresses=${vcap.services.reservations-rabbitmq.credentials.uri}
#spring.rabbitmq.addresses = ${vcap.services.reservations-rabbitmq.credentials.uri}
#spring.rabbitmq.host=${vcap.services.reservations-rabbitmq.credentials.uri}