# Logging Levels:
logging:
  level: 
    com.netflix: INFO # Overriding centrally managed log levels for this particular service..

# Actuator Endpoint Configurations
info: # /actuator/info
  app:
    description: "A CANARY version of the service to place and review reservations."

spring:
  cloud:
    gateway:
      rsocket:
        client:
          service-name: reservation-service
          route-id: 401
          tags: # additional service metadata (similar to Eureka metadata tags)
            instance_name: reservation-service-2-canary
            version: 2.0-CANARY # version indicates that this is a canary instance
          broker: # where to find the gateway RSocket broker
            host: localhost # TODO: inject from environment for Cloud deployments.
            port: 7002      # TODO: connect via websocket, not TCP.
          
